### ISSUE TITLE
This function is not working on Matlab. Any suggestions?

### ISSUE THREAD

**Issue by saraF2021** [nghiaho12/rigid_transform_3D#10]
I tried this function on Matlab and it is not working. 
I tried as well the validation and I am receiving this error message:

"File: rigid_transform_3D.m Line: 7 Column: 15
Invalid use of operator.
Error in Validationrigidtransform (line 23)
[ret_R, ret_t] = rigid_transform_3D(A, B); "
 
Do you have any sughestion? Thx!

**Comment by nghiaho12** [comment]
Try to pull again. I merged a PR that should fix this.
